// app/science/page.tsx
import { Divider } from '@nextui-org/divider';
import '../globals.css'
import { getScienceHighlightData } from '../science/contentParser';
import Image from 'next/image'
import Link from 'next/link'
import { MaterialGroup } from './materialGroup';

export default async function Science() {

	const data = await getScienceHighlightData();

	return (
		<div className="h-screen lg:flex flex-col py-8">
			<div className='text-center py-4'>
				<h1 className='text-5xl'>I do science</h1>
			</div>
			<div className=''>
				<div className='text-start'>
					<h3 className='text-2xl'>Summary</h3>
					<Divider className='my-4'/>
					<div className="lg:flex py-8 w-full lg:w-[840px]">
						<div className="flex-col justify-center">
							<div className="justify-center flex">
								<Image src='/static/images/portrait.jpg' alt="" width={147} height={147} className="rounded-full"/>
							</div>
							<div className="justify-center flex-col">
								<div className="text-3xl text-center dark:text-gray-300">Kaze W. K Wong</div>
								<div className="text-base text-center dark:text-gray-300">Assistant research professor</div>
								<div className=" text-base text-center dark:text-gray-300">Johns Hopkins University</div>
							</div>
						</div>
						<div className="px-4 lg:w-2/3">
							<div className=" text-xl flex-row justify-start">
								<p className="py-3 text-base">
								I am an assistant research professor in the Department of Applied Mathematics and Statistics at Johns Hopkins University. I am also a software engineer with the Data Science and AI Institute.
								
								I have very broad interest in many different subjects. In brief, I spend 20-30% of my time thinking about <strong>astrophysics</strong>, ~40% of my time trying to <strong>understand to make neural network robust and how to make them go fast</strong>, and the remaining time <strong>building production-grade domain science applications</strong>. My work is primarily computational and I care about <strong>open source software</strong> a lot. See below for some of the topics I am currently working on. 
								
								<div className='flex flex-col py-4'>
									<div className='flex flex-row py-2'>
										<p className='px-2'>
											<a href="https://kazewong.github.io/CV">
												<img src="https://img.shields.io/badge/My-CV-blue?style=for-the-badge" alt="" className="h-6"/>
											</a>
										</p>

									</div>
									<div className='flex flex-row py-2'>
										<p className='px-2'>
											<a href="https://inspirehep.net/authors/1789361?ui-citation-summary=true">
												<img src="https://img.shields.io/badge/publication-inspire-green?style=for-the-badge" alt="" className="h-6"/>
											</a>
										</p>
										<p className='px-2'>
											<a href="https://scholar.google.com/citations?user=oQDoPMsAAAAJ&hl=en">
												<img src="https://img.shields.io/badge/publication-google-green?style=for-the-badge" alt="" className="h-6"/>
											</a>
										</p>

									</div>
									<div className='flex flex-row py-2'>
										<p className='px-2'>
											<img src="https://img.shields.io/github/stars/kazewong"/>
										</p>
									</div>
								</div>

								</p>
							</div>
						</div>
					</div>
				</div>

				<div className='text-start'>
					<h3 className='text-2xl'>Research Highlight</h3>
					<Divider className='my-4'/>
						<p className='px-4 py-2'>
							Here are some topics I am or have been working on. I am big believer in collaborative work instead of racing against each other, so if you find any of the following topics interested you, feel free to reach out to me.
						</p>
						<div className="flex-column">
							{data.map((HighlighData) => (
								<div className="p-2">
									<Link href={HighlighData.link} className='text-cyan-500 text-large'>{HighlighData.title}</Link>
									<div className="text-san">{HighlighData.description}</div>
								</div>	
							))}
						</div>
				</div>

				<div className='text-start'>
					<h3 className='text-2xl'>Machine learning clinic</h3>
					<Divider className='my-4'/>
						<p className='px-4 py-2'>
							
						</p>
				</div>
			</div>
		</div>
	);
}

// src/routes/(content)/science/+page.svelte
<script>
	import portrait from '$lib/assets/images/portrait.jpg';
	import ResponsiveCard from '../../../components/ResponsiveCard.svelte';
	import HighlightItem from './HighlightItem.svelte';

	import highlight_data_file from './highlight_data.json';

	const highlight_data = highlight_data_file.items.map((item) => {
		return {
			image: item.image,
			title: item.title,
			description: item.description,
			alt_des: item.alt_des,
			date: item.date,
			link: item.link,
		};
	});

	let highlight_current_id = $state(0);
</script>

<h1 class="flex justify-center text-6xl">I Do Science</h1>

<div class="block">
	<div class="divider dark:divider-primary divider-start">
		<h3 class="text-4xl">Who am I</h3>
	</div>
	
	<div class="w-full flex justify-center">
		<div class="lg:flex justify-items-center py-8 lg:w-4xl">
			<!-- Portrait -->
			<div class="flex-col justify-center w-4/5 lg:w-2/5">
				<div class="justify-center flex">
					<img src={portrait} alt="" width={147} height={147} class="rounded-full" />
				</div>
				<div class="justify-center flex-col">
					<h2 class="text-4xl text-center p-0">Kaze W. K Wong</h2>
					<h3 class="text-xl text-center p-0">Assistant Research Professor</h3>
					<h3 class="text-xl text-center p-0">Research Software Engineer</h3>
					<h3 class=" text-xl text-center p-0">Johns Hopkins University</h3>
				</div>
			</div>
	
			<!-- Description -->
			<div class=" lg:w-3/5 text-justify">
				<p>
					I am an assistant research professor in the Department of Applied Mathematics and Statistics
					at Johns Hopkins University. I am also a software engineer with the Data Science and AI
					Institute. I have very broad interest in many different subjects. In brief, I spend 20-30%
					of my time thinking about <strong>astrophysics</strong>, ~40% of my time trying to
					<strong>understand to make neural network robust and how to tune them</strong>, and the
					remaining time <strong>building production-grade domain science applications</strong>. My
					work is primarily computational and I care about <strong>open source software</strong> a lot.
					See below for some of the topics I am currently working on.
				</p>
			</div>
		</div>
	</div>
	
</div>

<div class="block">
	<div class="divider dark:divider-primary divider-start">
		<h3 class="text-4xl">Link tree</h3>
	</div>
	
	<div class="flex justify-center gap-4">
		<a href="https://github.com/kazewong/CV/blob/main/cv.pdf">
			<button class="btn btn-accent btn-xs sm:btn-sm md:btn-md lg:btn-lg xl:btn-xl">
					CV
			</button>
		</a>
		<a href="https://inspirehep.net/authors/1789361?ui-citation-summary=true">
			<button class="btn btn-accent btn-xs sm:btn-sm md:btn-md lg:btn-lg xl:btn-xl">
					InspireHEP
			</button>
		</a>
		<a href="https://scholar.google.com/citations?user=oQDoPMsAAAAJ&hl=en">
			<button class="btn btn-accent btn-xs sm:btn-sm md:btn-md lg:btn-lg xl:btn-xl">
					Google Scholar
			</button>
		</a>
		<a href="https://ui.adsabs.harvard.edu/search/p_=0&q=%3Dauthor%3A%22Wong%2C%20Kaze%20W.%20K.%22&sort=date%20desc%2C%20bibcode%20desc">
			<button class="btn btn-accent btn-xs sm:btn-sm md:btn-md lg:btn-lg xl:btn-xl">
					NASA/ADS
			</button>
		</a>
	</div>	
</div>



<div class="block">
	<div class="divider dark:divider-primary divider-start pb-4">
		<h3 class="text-4xl">Research Interest</h3>
	</div>

	<p>
		Here are 
	</p>
	
	{#each highlight_data as item,index}
		<div class="w-full py-4">
			<HighlightItem
				image={item.image}
				title={item.title}
				description={item.description}
				alt_des={item.alt_des}
				date={item.date}
				left={index % 2 == 0}
				link={item.link}
			/>
		</div>	
	{/each}
</div>


<!-- <h1 class="bg-linear-to-r from-red-500 via-yellow-300 to-indigo-40 text-transparent bg-clip-text">
	Under constrcution
</h1> -->

<div class="block">
	<div class="divider dark:divider-primary divider-start">
		<h3 class="text-4xl">Research projects</h3>
	</div>
	
	<p>
	I only take students that are either directly recommended by my collaborators or students at Johns Hopkins University.
	</p>
</div>
